"""Añade campo created a Post

Revision ID: f8b2d199d006
Revises: 542c2e1d09f8
Create Date: 2022-05-21 17:30:32.746879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b2d199d006'
down_revision = '542c2e1d09f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created')
    # ### end Alembic commands ###
